export const chats = [
  { title: "Exploring AI's Role in Healthcare", icon: "/icons/message.svg" },
  { title: "Learning the Basics of Python Programming", icon: "/icons/message.svg" },
  { title: "Creating a Workout Plan for Beginners", icon: "/icons/message.svg" },
  { title: "Understanding Climate Change Effects", icon: "/icons/message.svg" },
  { title: "Discussing the Future of Electric Cars", icon: "/icons/message.svg" },
  { title: "Writing a Business Plan for a Startup", icon: "/icons/message.svg" },
  { title: "Explaining Blockchain Technology", icon: "/icons/message.svg" },
  { title: "Generating Ideas for a Sci-Fi Story", icon: "/icons/message.svg" },
  { title: "Planning a Two-Week European Vacation", icon: "/icons/message.svg" },
  { title: "Analyzing the Causes of World War II", icon: "/icons/message.svg" },
  { title: "Cooking Tips for Beginners", icon: "/icons/message.svg" },
  { title: "Understanding the Basics of Machine Learning", icon: "/icons/message.svg" },
  { title: "Discussing the Benefits of Mindfulness", icon: "/icons/message.svg" },
  { title: "Exploring Renewable Energy Solutions", icon: "/icons/message.svg" },
  { title: "How to Start a Freelancing Career", icon: "/icons/message.svg" },
  { title: "Learning About Space Exploration Milestones", icon: "/icons/message.svg" },
  { title: "Understanding Cryptocurrency Investments", icon: "/icons/message.svg" },
  { title: "Writing a Compelling College Application Essay", icon: "/icons/message.svg" },
  { title: "Explaining How the Internet Works", icon: "/icons/message.svg" },
  { title: "Tips for Improving Public Speaking Skills", icon: "/icons/message.svg" },
];
